version: '2'
services:
  web:
    image: nginx:1.8
    ports:
      - 8081:80
    links:
      - php
    volumes:
      - ./src:/var/www/html
      - ./docker/web/conf.d:/etc/nginx/conf.d
  php:
    build: ./docker/php
    links:
      - db
    volumes:
      - ./src:/var/www/html
    environment:
      DB_NAME: wordpress
      DB_USER: wp
      DB_PASSWORD: p4ssw0rd
      DB_HOST: db
      WP_ENV: development
      WP_HOME: http://192.168.99.100:8081
      WP_SITEURL: http://192.168.99.100:8081/wp
      AUTH_KEY: 'generateme'
      SECURE_AUTH_KEY: 'generateme'
      LOGGED_IN_KEY: 'generateme'
      NONCE_KEY: 'generateme'
      AUTH_SALT: 'generateme'
      SECURE_AUTH_SALT: 'generateme'
      LOGGED_IN_SALT: 'generateme'
      NONCE_SALT: 'generateme'
  db:
    image: mysql
    ports:
      - 3306:3306
    command: "/run/run.sh" # remove if you dont want to mount db data
    volumes:
      - ./data/db/mysql:/var/lib/mysql:rw # remove if you dont want to mount db data
      - ./docker/db/run.sh:/run/run.sh:rw # remove if you dont want to mount db data
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: p4ssw0rd
      MYSQL_ROOT_PASSWORD: p4ssw0rd2
